#!/bin/bash

set -euo pipefail

defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

REPO_PATH="${CI_PRIMARY_REPOSITORY_PATH:-${GITHUB_WORKSPACE:-$(pwd)}}"
CLIENTS_PATH="${REPO_PATH}/BatFiKit/Sources/ClientsLive"
INSTALLER_PATH="${REPO_PATH}/Installer"

if [[ ! -d "${CLIENTS_PATH}" ]]; then
    echo "Directory not found: ${CLIENTS_PATH}" >&2
    exit 1
fi

if [[ ! -d "${INSTALLER_PATH}" ]]; then
    echo "Directory not found: ${INSTALLER_PATH}" >&2
    exit 1
fi

escaped_swift_string() {
    python3 -c 'import json,sys; print(json.dumps(sys.argv[1]))' "$1"
}

create_analytics_dsn_file() {
    local dsn="${SENTRY_DSN:-}"
    local dsn_literal
    dsn_literal="$(escaped_swift_string "${dsn}")"

    cat > "${CLIENTS_PATH}/AnalyticsDSN.swift" <<EOF
import Foundation

// This file is automatically generated in CI.
// Do not modify or check into version control.
let analyticsDSN = ${dsn_literal}
EOF
}

create_installer_url_file() {
    local download_url="${BATFI_DOWNLOAD_URL:-${INSTALLER_DOWNLOAD_URL:-}}"
    local warning=""

    if [[ -z "${download_url}" ]]; then
        download_url="https://example.invalid/BatFi.zip"
        warning="BATFI_DOWNLOAD_URL is not set. Using placeholder URL."
    fi

    local download_url_literal
    download_url_literal="$(escaped_swift_string "${download_url}")"

    cat > "${INSTALLER_PATH}/URL.swift" <<EOF
import Foundation

// This file is automatically generated in CI.
// Do not modify or check into version control.
let sessionConfig: URLSessionConfiguration = {
    let configuration = URLSessionConfiguration.default
    configuration.waitsForConnectivity = true
    configuration.timeoutIntervalForRequest = 130
    configuration.timeoutIntervalForResource = 130
    return configuration
}()

let url = URL(string: ${download_url_literal})!
EOF

    if [[ -n "${warning}" ]]; then
        echo "warning: ${warning}" >&2
    fi
}

create_analytics_dsn_file
create_installer_url_file

echo "Generated CI Swift files:"
echo "- ${CLIENTS_PATH}/AnalyticsDSN.swift"
echo "- ${INSTALLER_PATH}/URL.swift"
